# Site settings
title: Matthew Shirtliffe
tag: Browser, Editor and Terminal
# header-img: img/home-bg.jpg
email: me@matthewshirtliffe.co.uk
copyright_name: Matthew Shirtliffe
description: "A blog by Matthew Shirtliffe on mobile and web development, and business."
baseurl: ""
url: "https://www.matthewshirtliffe.co.uk"
twitter_username: mattshirtliffe
github_username:  mattshirtliffe
email_username:  me@matthewshirtliffe.co.uk

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed, jekyll-gist, jekyll-seo-tag]

sass:
  cache: false
