# Site settings
title: Matthew Shirtliffe
tag: Lifestyle Programmer
# header-img: img/home-bg.jpg
email: me@matthewshirtliffe.co.uk
copyright_name: Matthew Shirtliffe
description: "Applications Developer specialising in delivering robust, secure and scalable solutions."
baseurl: ""
url: "http://www.matthewshirtliffe.co.uk"
twitter_username: mattshirtliffe
github_username:  mattshirtliffe
email_username:  me@matthewshirtliffe.co.uk

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-gist]


sass:
  cache: false
